# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  install_ubuntu:
    cmds:
      - echo "Installation for Ubuntu (using Taskdev file)"
      - sudo apt install -y git openssh-server feh zip unzip
      - sudo apt install -y fonts-font-awesome  powerline #ttf-dejavu
      - sudo apt install -y keepassxc
      - sudo apt install -y fzf fasd
      - sudo apt install -y zsh tmux stow
      - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      - |
        cd $HOME/personal

        # git clone https://github.com/jombo-jon/playbook.git
        # yip file
        cd playbook


    silent: false

  install_arch:
    cmds:
      - |
        echo "Installation for Arch (using Taskdev file)"
    silent: true

  make:
    cmds:
      - |
        sudo pacman -S git openssh feh zip unzip
        sudo pacman -S ttf-font-awesome ttf-dejavu powerline
        sudo pacman -S keepassxc
        sudo pacman -S fzf fasd
        sudo pacman -S zsh tmux
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    silent: true

