# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}} nf"
    silent: true
  
  install:
    cmds:
      - cd _nf
      - make clean
      - make install
    silent: true

  stow:
    cmds:
      - stow --target=$HOME .
    silent: true

  unstow:
    cmds:
        - stow -D --target=$HOME .
    silent: true
