#!/bin/bash

# Gets the wifi status

# WIFI_FULL_ICON=''
# WIFI_MID_ICON=''
# WIFI_LOW_ICON=''
# NO_WIFI_ICON=' '

get_ethernet()
{
        # ssid=$(iwgetid -r)
        # if [[ ! -z $ssid ]]
        # then
            ipv4=$(hostname -I | awk '{print $2}') 
            echo $ipv4 
        # else
        #     echo $NO_WIFI_ICON "/---/---.---.---.---" 
        # fi

        # if grep -q wl* "/proc/net/wireless"; then
        #         # Wifi SSID

        #         ssid =$(iwgetid -r)
        #         if [ -z $ssid ]
        #         then
        #             echo $WIFI_FULL_ICON " - " $ssid 
        #         else
        #             echo $NO_WIFI_ICON " - ---" 
        #         fi


                # Wifi quality percentage
                # percentage=$(grep "^\s*w" /proc/net/wireless | awk '{ print "", int($3 * 100 / 70)}'| xargs)
                # case $percentage in
                #         0)                              echo $NO_WIFI_ICON;;
                #         100|9[0-9]|8[0-9]|7[0-9])       echo "$WIFI_FULL_ICON" ;;
                #         6[0-9]|5[0-9]|4[0-9]|3[0-9])    echo "$WIFI_MID_ICON" ;;
                #         2[0-9]|1[0-9]|[0-9])            echo "$WIFI_LOW_ICON" ;;
                # esac
        # fi
}

get_ethernet

