# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}} dmenu"
    silent: true
  
  make:
    cmds:
      - |
        cd _dmenu
        sudo make install
    silent: true
